// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMty_qp_11J1uEzA5CfV8MjgOjdi5pyM',
    appId: '1:7728393642:android:fc4ae8997c8a2e56c54fd3',
    messagingSenderId: '7728393642',
    projectId: 'umate-ad270',
    storageBucket: 'umate-ad270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ER_uyTeS5xQMcj2R4lLId0_mYgQ9sUg',
    appId: '1:7728393642:ios:e180eea00e7d83d1c54fd3',
    messagingSenderId: '7728393642',
    projectId: 'umate-ad270',
    storageBucket: 'umate-ad270.appspot.com',
    iosBundleId: 'com.vanillajaem.umate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlna45ZYf7fFW2TnL86d15_BAVyAxDSc',
    appId: '1:7728393642:web:3e1eb1f3cd09286ec54fd3',
    messagingSenderId: '7728393642',
    projectId: 'umate-ad270',
    authDomain: 'umate-ad270.firebaseapp.com',
    storageBucket: 'umate-ad270.appspot.com',
    measurementId: 'G-974WD64JRX',
  );

}